// Ephemeral, external interoperability harness for ZeroS3 M5-A: SigV4
// query-string authentication (presigned GET/PUT), the "zeros3 presign"
// CLI, and virtual-hosted-style addressing.
//
// This program is NOT part of ZeroS3, is never linked into
// the zeros3 binary, and pulls in the pinned AWS SDK for Go v2 modules purely as
// a black-box client. Every presigned URL exercised here is generated by
// the real AWS SDK's own presign client (s3.PresignClient) and then
// fetched/uploaded with an ordinary net/http.Client carrying no S3-
// specific signing logic of its own -- proving interoperability with a
// real, unmodified SDK rather than a ZeroS3-specific workflow. A second
// pass repeats the positive GET/PUT cases through the "zeros3 presign"
// CLI binary itself and through virtual-hosted-style addressing.
package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

const (
	accessKeyID     = "AKIAZEROS3EXAMPLE01"
	secretAccessKey = "zeros3exampleSecretKeyForM1TestingOnly01"
	region          = "us-east-1"
	vhostBase       = "s3.zeros3-harness.test"
)

var pass, fail int

func check(name string, err error) {
	if err != nil {
		fail++
		fmt.Printf("FAIL: %s: %v\n", name, err)
		return
	}
	pass++
	fmt.Printf("PASS: %s\n", name)
}

func requireTrue(name string, cond bool, detail string) {
	if !cond {
		fail++
		fmt.Printf("FAIL: %s: %s\n", name, detail)
		return
	}
	pass++
	fmt.Printf("PASS: %s\n", name)
}

// expectError asserts an operation FAILED -- used throughout the negative/
// adversarial cases below, where success would itself be the bug.
func expectError(name string, err error) {
	if err == nil {
		fail++
		fmt.Printf("FAIL: %s: expected an error, got success\n", name)
		return
	}
	pass++
	fmt.Printf("PASS: %s (correctly rejected: %v)\n", name, err)
}

func expectHTTPStatus(name string, resp *http.Response, err error, want int) {
	if err != nil {
		fail++
		fmt.Printf("FAIL: %s: request error: %v\n", name, err)
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode != want {
		body, _ := io.ReadAll(resp.Body)
		fail++
		fmt.Printf("FAIL: %s: status %d, want %d (body: %s)\n", name, resp.StatusCode, want, truncate(string(body), 300))
		return
	}
	pass++
	fmt.Printf("PASS: %s (status %d)\n", name, resp.StatusCode)
}

// expectHTTPNotOK asserts a response is NOT a 2xx success -- used for
// negative presign cases where the exact rejection status (403 vs 400)
// matters less than "this must not have succeeded."
func expectHTTPNotOK(name string, resp *http.Response, err error) {
	if err != nil {
		fail++
		fmt.Printf("FAIL: %s: request error: %v\n", name, err)
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		body, _ := io.ReadAll(resp.Body)
		fail++
		fmt.Printf("FAIL: %s: expected rejection, got status %d (body: %s)\n", name, resp.StatusCode, truncate(string(body), 300))
		return
	}
	pass++
	fmt.Printf("PASS: %s (correctly rejected with status %d)\n", name, resp.StatusCode)
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

func freePort() (string, error) {
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return "", err
	}
	defer l.Close()
	return l.Addr().String(), nil
}

func startZeroS3(binPath, storeDir, addr string, extraArgs ...string) (*exec.Cmd, error) {
	args := append([]string{"serve", "-store", storeDir, "-addr", addr}, extraArgs...)
	cmd := exec.Command(binPath, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return nil, err
	}
	deadline := time.Now().Add(5 * time.Second)
	for time.Now().Before(deadline) {
		conn, err := net.Dial("tcp", addr)
		if err == nil {
			conn.Close()
			return cmd, nil
		}
		time.Sleep(50 * time.Millisecond)
	}
	cmd.Process.Kill()
	return nil, fmt.Errorf("zeros3 did not start listening on %s in time", addr)
}

// vhostRedirectClient returns a plain net/http.Client whose Transport
// dials the real server address regardless of the URL's hostname, while
// leaving the Host header exactly as the caller set it -- the standard
// technique for testing virtual-hosted-style addressing without real DNS
// for the vhost domain.
func vhostRedirectClient(realAddr string) *http.Client {
	return &http.Client{
		Transport: &http.Transport{
			DialContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
				var d net.Dialer
				return d.DialContext(ctx, network, realAddr)
			},
		},
	}
}

// newSigningClient builds an S3 client against endpoint. httpClient, if
// non-nil, is applied directly to s3.Options.HTTPClient (not via
// config.WithHTTPClient) -- config.LoadDefaultConfig's own custom-HTTP-
// client path additionally tries to layer this environment's proxy CA
// bundle onto the client, which requires a client type the SDK doesn't
// otherwise need here; setting it on s3.Options after config load avoids
// that entirely while still redirecting every S3 request appropriately.
func newSigningClient(endpoint string, usePathStyle bool, httpClient *http.Client) *s3.Client {
	ctx := context.Background()
	cfg, err := config.LoadDefaultConfig(ctx,
		config.WithRegion(region),
		config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(accessKeyID, secretAccessKey, "")),
	)
	if err != nil {
		log.Fatalf("config.LoadDefaultConfig: %v", err)
	}
	return s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.BaseEndpoint = aws.String(endpoint)
		o.UsePathStyle = usePathStyle
		if httpClient != nil {
			o.HTTPClient = httpClient
		}
	})
}

func sha256Hex(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

func main() {
	binPath := os.Getenv("ZEROS3_BIN")
	if binPath == "" {
		binPath = "./zeros3-bin"
	}
	storeDir, err := os.MkdirTemp("", "zeros3-presign-harness-store-")
	if err != nil {
		log.Fatal(err)
	}
	defer os.RemoveAll(storeDir)

	addr, err := freePort()
	if err != nil {
		log.Fatal(err)
	}
	cmd, err := startZeroS3(binPath, storeDir, addr, "-vhost-base", vhostBase)
	if err != nil {
		log.Fatalf("starting zeros3: %v", err)
	}
	defer func() {
		cmd.Process.Kill()
		cmd.Wait()
	}()

	endpoint := "http://" + addr
	client := newSigningClient(endpoint, true, nil)
	presigner := s3.NewPresignClient(client)
	ctx := context.Background()

	bucket := "presign-bucket"
	_, err = client.CreateBucket(ctx, &s3.CreateBucketInput{Bucket: aws.String(bucket)})
	check("CreateBucket", err)

	// ==========================================================================
	// Phase C -- presigned GET (positive)
	// ==========================================================================

	getKey := "greeting.txt"
	getBody := []byte("hello from a real AWS SDK presigned GET, plain HTTP client on the far end")
	_, err = client.PutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(bucket), Key: aws.String(getKey), Body: bytes.NewReader(getBody), ContentType: aws.String("text/plain"),
	})
	check("seed PutObject for presigned GET", err)

	getPresignResult, err := presigner.PresignGetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(bucket), Key: aws.String(getKey),
	}, s3.WithPresignExpires(5*time.Minute))
	check("PresignGetObject", err)
	if getPresignResult != nil {
		plainGetReq, _ := http.NewRequest(getPresignResult.Method, getPresignResult.URL, nil)
		resp, err := http.DefaultClient.Do(plainGetReq)
		if err == nil {
			defer resp.Body.Close()
			data, readErr := io.ReadAll(resp.Body)
			check("presigned GET via ordinary http.Client", readErr)
			requireTrue("presigned GET status 200", resp.StatusCode == http.StatusOK, fmt.Sprintf("got %d", resp.StatusCode))
			requireTrue("presigned GET exact byte equality", bytes.Equal(data, getBody), "byte mismatch")
			requireTrue("presigned GET exact sha256", sha256Hex(data) == sha256Hex(getBody), "hash mismatch")
			requireTrue("presigned GET Content-Type preserved", resp.Header.Get("Content-Type") == "text/plain",
				fmt.Sprintf("got %q", resp.Header.Get("Content-Type")))
		} else {
			fail++
			fmt.Printf("FAIL: presigned GET request: %v\n", err)
		}

		// ---- negative cases (presigned GET) ----
		altPath := strings.Replace(getPresignResult.URL, getKey, "not-"+getKey, 1)
		resp, err = http.Get(altPath)
		expectHTTPNotOK("presigned GET: altered object path", resp, err)

		altBucket := strings.Replace(getPresignResult.URL, "/"+bucket+"/", "/not-"+bucket+"/", 1)
		resp, err = http.Get(altBucket)
		expectHTTPNotOK("presigned GET: altered bucket", resp, err)

		modParam := strings.Replace(getPresignResult.URL, "X-Amz-Expires=300", "X-Amz-Expires=299", 1)
		if modParam == getPresignResult.URL {
			// Expires may not be exactly 300s depending on SDK internals; fall back to SignedHeaders.
			modParam = strings.Replace(getPresignResult.URL, "host", "hostx", 1)
		}
		resp, err = http.Get(modParam)
		expectHTTPNotOK("presigned GET: modified signed query parameter", resp, err)

		modSig := reAppendTamperedChar(getPresignResult.URL, "X-Amz-Signature=")
		resp, err = http.Get(modSig)
		expectHTTPNotOK("presigned GET: modified signature", resp, err)

		modHostReq, _ := http.NewRequest(http.MethodGet, getPresignResult.URL, nil)
		modHostReq.Host = "attacker.example:" + addrPort(addr)
		resp, err = http.DefaultClient.Do(modHostReq)
		expectHTTPNotOK("presigned GET: modified signed Host header", resp, err)

		expiredPresign, err := presigner.PresignGetObject(ctx, &s3.GetObjectInput{
			Bucket: aws.String(bucket), Key: aws.String(getKey),
		}, s3.WithPresignExpires(1*time.Second))
		check("PresignGetObject (short-lived, for expiry test)", err)
		if expiredPresign != nil {
			time.Sleep(2 * time.Second)
			resp, err = http.Get(expiredPresign.URL)
			expectHTTPNotOK("presigned GET: expired URL", resp, err)
		}

		wrongRegionCfg, _ := config.LoadDefaultConfig(ctx,
			config.WithRegion("eu-west-1"),
			config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(accessKeyID, secretAccessKey, "")),
		)
		wrongRegionClient := s3.NewFromConfig(wrongRegionCfg, func(o *s3.Options) {
			o.BaseEndpoint = aws.String(endpoint)
			o.UsePathStyle = true
		})
		wrongRegionPresigner := s3.NewPresignClient(wrongRegionClient)
		wrongScopeResult, err := wrongRegionPresigner.PresignGetObject(ctx, &s3.GetObjectInput{
			Bucket: aws.String(bucket), Key: aws.String(getKey),
		}, s3.WithPresignExpires(5*time.Minute))
		check("PresignGetObject with wrong region (for credential-scope test)", err)
		if wrongScopeResult != nil {
			resp, err = http.Get(wrongScopeResult.URL)
			expectHTTPNotOK("presigned GET: wrong credential scope (region)", resp, err)
		}
	}

	// ==========================================================================
	// Phase D -- presigned PUT (positive + mutation-safety negatives)
	// ==========================================================================

	putKey := "uploaded-via-presigned-put.bin"
	putBody := []byte("payload uploaded through a real AWS SDK presigned PUT and a plain HTTP client")

	putPresignResult, err := presigner.PresignPutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(bucket), Key: aws.String(putKey),
	}, s3.WithPresignExpires(5*time.Minute))
	check("PresignPutObject", err)
	if putPresignResult != nil {
		putReq, _ := http.NewRequest(putPresignResult.Method, putPresignResult.URL, bytes.NewReader(putBody))
		resp, err := http.DefaultClient.Do(putReq)
		expectHTTPStatus("presigned PUT via ordinary http.Client", resp, err, http.StatusOK)

		getResp, err := client.GetObject(ctx, &s3.GetObjectInput{Bucket: aws.String(bucket), Key: aws.String(putKey)})
		check("ordinary signed GET after presigned PUT", err)
		if getResp != nil {
			data, _ := io.ReadAll(getResp.Body)
			getResp.Body.Close()
			requireTrue("presigned PUT byte equality (verified via ordinary signed GET)", bytes.Equal(data, putBody), "byte mismatch")
			requireTrue("presigned PUT sha256 equality", sha256Hex(data) == sha256Hex(putBody), "hash mismatch")
		}
		headResp, err := client.HeadObject(ctx, &s3.HeadObjectInput{Bucket: aws.String(bucket), Key: aws.String(putKey)})
		check("ordinary signed HEAD after presigned PUT", err)
		if headResp != nil {
			requireTrue("presigned PUT Content-Length via HEAD", aws.ToInt64(headResp.ContentLength) == int64(len(putBody)),
				fmt.Sprintf("got %d, want %d", aws.ToInt64(headResp.ContentLength), len(putBody)))
		}
	}

	// ---- negative cases (presigned PUT): must never mutate/create the object ----
	negKey := "should-never-exist.bin"
	negBody := []byte("this must never become visible")

	negPresign, err := presigner.PresignPutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(bucket), Key: aws.String(negKey),
	}, s3.WithPresignExpires(5*time.Minute))
	check("PresignPutObject (for negative cases)", err)
	if negPresign != nil {
		tamperedPath := strings.Replace(negPresign.URL, negKey, "tampered-"+negKey, 1)
		resp, err := http.DefaultClient.Do(mustPutReq(tamperedPath, negBody))
		expectHTTPNotOK("presigned PUT: tampered path", resp, err)
		assertObjectAbsent(ctx, client, bucket, "tampered-"+negKey)

		tamperedSig := reAppendTamperedChar(negPresign.URL, "X-Amz-Signature=")
		resp, err = http.DefaultClient.Do(mustPutReq(tamperedSig, negBody))
		expectHTTPNotOK("presigned PUT: tampered signature", resp, err)
		assertObjectAbsent(ctx, client, bucket, negKey)

		modHostReq := mustPutReq(negPresign.URL, negBody)
		modHostReq.Host = "attacker.example:" + addrPort(addr)
		resp, err = http.DefaultClient.Do(modHostReq)
		expectHTTPNotOK("presigned PUT: modified required signed header (Host)", resp, err)
		assertObjectAbsent(ctx, client, bucket, negKey)
	}

	shortLivedPresign, err := presigner.PresignPutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(bucket), Key: aws.String(negKey),
	}, s3.WithPresignExpires(1*time.Second))
	check("PresignPutObject (short-lived, for expiry test)", err)
	if shortLivedPresign != nil {
		time.Sleep(2 * time.Second)
		resp, err := http.DefaultClient.Do(mustPutReq(shortLivedPresign.URL, negBody))
		expectHTTPNotOK("presigned PUT: expired URL", resp, err)
		assertObjectAbsent(ctx, client, bucket, negKey)
	}

	// ==========================================================================
	// zeros3 presign CLI: generate URLs with the CLI binary itself and
	// prove they pass the exact same server verifier as SDK-generated ones.
	// ==========================================================================

	cliKey := "cli-presigned-object.txt"
	cliBody := []byte("uploaded by curl-equivalent plain HTTP, using a zeros3-presign-CLI-generated URL")
	cliPutURL, err := runPresignCLI(binPath, "put", bucket, cliKey, endpoint, "5m", false)
	check("zeros3 presign put (CLI)", err)
	if cliPutURL != "" {
		resp, err := http.DefaultClient.Do(mustPutReq(cliPutURL, cliBody))
		expectHTTPStatus("CLI-generated presigned PUT", resp, err, http.StatusOK)
	}
	cliGetURL, err := runPresignCLI(binPath, "get", bucket, cliKey, endpoint, "5m", false)
	check("zeros3 presign get (CLI)", err)
	if cliGetURL != "" {
		resp, err := http.Get(cliGetURL)
		if err == nil {
			defer resp.Body.Close()
			data, _ := io.ReadAll(resp.Body)
			requireTrue("CLI-generated presigned GET status+bytes", resp.StatusCode == http.StatusOK && bytes.Equal(data, cliBody),
				fmt.Sprintf("status %d, got %d bytes", resp.StatusCode, len(data)))
		} else {
			fail++
			fmt.Printf("FAIL: CLI-generated presigned GET: %v\n", err)
		}
	}
	if !strings.Contains(cliPutURL+cliGetURL, secretAccessKey) {
		pass++
		fmt.Println("PASS: CLI-generated presigned URLs never contain the raw secret access key")
	} else {
		fail++
		fmt.Println("FAIL: CLI-generated presigned URL leaked the secret access key")
	}

	// ==========================================================================
	// Phase F -- virtual-hosted-style addressing, via both the SDK presign
	// client (UsePathStyle:false) and the zeros3 presign CLI's -vhost flag.
	// ==========================================================================

	vhClient := vhostRedirectClient(addr)
	vhostEndpoint := "http://" + vhostBase + ":" + addrPort(addr)
	vhostS3Client := newSigningClient(vhostEndpoint, false, vhClient)
	vhostPresigner := s3.NewPresignClient(vhostS3Client)

	vhKey := "vhost-object.txt"
	vhBody := []byte("payload round-tripped entirely through virtual-hosted-style addressing")
	_, err = vhostS3Client.PutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(bucket), Key: aws.String(vhKey), Body: bytes.NewReader(vhBody),
	})
	check("virtual-hosted-style ordinary signed PutObject", err)

	getObj, err := vhostS3Client.GetObject(ctx, &s3.GetObjectInput{Bucket: aws.String(bucket), Key: aws.String(vhKey)})
	check("virtual-hosted-style ordinary signed GetObject", err)
	if getObj != nil {
		data, _ := io.ReadAll(getObj.Body)
		getObj.Body.Close()
		requireTrue("virtual-hosted-style GetObject byte equality", bytes.Equal(data, vhBody), "byte mismatch")
	}

	vhPresignGet, err := vhostPresigner.PresignGetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(bucket), Key: aws.String(vhKey),
	}, s3.WithPresignExpires(5*time.Minute))
	check("PresignGetObject via virtual-hosted-style client", err)
	if vhPresignGet != nil {
		requireTrue("virtual-hosted-style presigned URL has bucket in Host, not path",
			strings.Contains(vhPresignGet.URL, bucket+"."+vhostBase) && !strings.Contains(vhPresignGet.URL, "/"+bucket+"/"),
			vhPresignGet.URL)
		req, _ := http.NewRequest(http.MethodGet, vhPresignGet.URL, nil)
		resp, err := vhClient.Do(req)
		if err == nil {
			defer resp.Body.Close()
			data, _ := io.ReadAll(resp.Body)
			requireTrue("virtual-hosted-style presigned GET status+bytes", resp.StatusCode == http.StatusOK && bytes.Equal(data, vhBody),
				fmt.Sprintf("status %d, got %d bytes", resp.StatusCode, len(data)))
		} else {
			fail++
			fmt.Printf("FAIL: virtual-hosted-style presigned GET: %v\n", err)
		}
	}

	cliVHostPutURL, err := runPresignCLI(binPath, "put", bucket, "cli-vhost-object.txt", vhostEndpoint, "5m", true)
	check("zeros3 presign put -vhost (CLI)", err)
	if cliVHostPutURL != "" {
		req, _ := http.NewRequest(http.MethodPut, cliVHostPutURL, bytes.NewReader(vhBody))
		resp, err := vhClient.Do(req)
		expectHTTPStatus("CLI-generated virtual-hosted-style presigned PUT", resp, err, http.StatusOK)
	}

	fmt.Printf("\n===== SUMMARY: %d passed, %d failed =====\n", pass, fail)
	if fail > 0 {
		os.Exit(1)
	}
}

func addrPort(addr string) string {
	if idx := strings.LastIndex(addr, ":"); idx >= 0 {
		return addr[idx+1:]
	}
	return addr
}

func mustPutReq(rawURL string, body []byte) *http.Request {
	req, err := http.NewRequest(http.MethodPut, rawURL, bytes.NewReader(body))
	if err != nil {
		log.Fatalf("mustPutReq: %v", err)
	}
	return req
}

// reAppendTamperedChar flips one hex character right after marker in a
// presigned URL's query string -- used to corrupt X-Amz-Signature without
// disturbing anything else in the URL.
func reAppendTamperedChar(rawURL, marker string) string {
	idx := strings.Index(rawURL, marker)
	if idx < 0 {
		return rawURL
	}
	pos := idx + len(marker)
	if pos >= len(rawURL) {
		return rawURL
	}
	b := []byte(rawURL)
	if b[pos] == '0' {
		b[pos] = '1'
	} else {
		b[pos] = '0'
	}
	return string(b)
}

func assertObjectAbsent(ctx context.Context, client *s3.Client, bucket, key string) {
	_, err := client.HeadObject(ctx, &s3.HeadObjectInput{Bucket: aws.String(bucket), Key: aws.String(key)})
	expectError(fmt.Sprintf("mutation safety: %s/%s must not be visible", bucket, key), err)
}

// runPresignCLI shells out to the zeros3 binary's own "presign" subcommand
// and returns the single URL it prints on stdout.
func runPresignCLI(binPath, method, bucket, key, endpoint, expires string, vhost bool) (string, error) {
	args := []string{"presign", method,
		"-bucket", bucket, "-key", key,
		"-expires", expires,
		"-access-key", accessKeyID, "-secret-key", secretAccessKey,
		"-region", region, "-endpoint", endpoint,
	}
	if vhost {
		args = append(args, "-vhost")
	}
	cmd := exec.Command(binPath, args...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("%w (stderr: %s)", err, stderr.String())
	}
	return strings.TrimSpace(stdout.String()), nil
}
